name: Latest blog activity
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at 00:00 UTC
permissions:
      contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity from BLOG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "https://zhongye1.github.io/Arknight-notes/rss.xml"
          template: "<tr><td>$title</td><td>$url</td></tr>"
